=== Jakob-G/xml_assignment1/data/classes.dtd
<!ELEMENT classes ANY>
<!--Term0-->
<!ELEMENT set_0_A (Course+)>
<!ELEMENT set_0_B (Course+)>
<!ELEMENT set_0_C (Course+)>
<!ELEMENT set_0_D (Course+)>
<!ELEMENT set_0_E (Course+)>
<!ELEMENT set_0_F (Course+)>
<!ELEMENT set_0_G (Course+)>
<!ELEMENT set_0_H (Course+)>
<!ELEMENT set_0_I (Course+)>
<!ELEMENT set_0_J (Course+)>
<!ELEMENT set_0_K (Course+)>
<!ELEMENT set_0_L (Course+)>
<!ELEMENT set_0_M (Course+)>
<!ELEMENT set_0_N (Course+)>
<!ELEMENT set_0_O (Course+)>
<!ELEMENT set_0_P (Course+)>
<!ELEMENT set_0_Q (Course+)>
<!ELEMENT set_0_R (Course+)>
<!ELEMENT set_0_S (Course+)>
<!ELEMENT set_0_T (Course+)>
<!ELEMENT set_0_U (Course+)>
<!ELEMENT set_0_V (Course+)>
<!ELEMENT set_0_W (Course+)>
<!ELEMENT set_0_X (Course+)>
<!ELEMENT set_0_Y (Course+)>
<!ELEMENT set_0_Z (Course+)>
<!--Term1-->
<!ELEMENT set_1_A (Course+)>
<!ELEMENT set_1_B (Course+)>
<!ELEMENT set_1_C (Course+)>
<!ELEMENT set_1_D (Course+)>
<!ELEMENT set_1_E (Course+)>
<!ELEMENT set_1_F (Course+)>
<!ELEMENT set_1_G (Course+)>
<!ELEMENT set_1_H (Course+)>
<!ELEMENT set_1_I (Course+)>
<!ELEMENT set_1_J (Course+)>
<!ELEMENT set_1_K (Course+)>
<!ELEMENT set_1_L (Course+)>
<!ELEMENT set_1_M (Course+)>
<!ELEMENT set_1_N (Course+)>
<!ELEMENT set_1_O (Course+)>
<!ELEMENT set_1_P (Course+)>
<!ELEMENT set_1_Q (Course+)>
<!ELEMENT set_1_R (Course+)>
<!ELEMENT set_1_S (Course+)>
<!ELEMENT set_1_T (Course+)>
<!ELEMENT set_1_U (Course+)>
<!ELEMENT set_1_V (Course+)>
<!ELEMENT set_1_W (Course+)>
<!ELEMENT set_1_X (Course+)>
<!ELEMENT set_1_Y (Course+)>
<!ELEMENT set_1_Z (Course+)>
<!--Term2-->
<!ELEMENT set_2_A (Course+)>
<!ELEMENT set_2_B (Course+)>
<!ELEMENT set_2_C (Course+)>
<!ELEMENT set_2_D (Course+)>
<!ELEMENT set_2_E (Course+)>
<!ELEMENT set_2_F (Course+)>
<!ELEMENT set_2_G (Course+)>
<!ELEMENT set_2_H (Course+)>
<!ELEMENT set_2_I (Course+)>
<!ELEMENT set_2_J (Course+)>
<!ELEMENT set_2_K (Course+)>
<!ELEMENT set_2_L (Course+)>
<!ELEMENT set_2_M (Course+)>
<!ELEMENT set_2_N (Course+)>
<!ELEMENT set_2_O (Course+)>
<!ELEMENT set_2_P (Course+)>
<!ELEMENT set_2_Q (Course+)>
<!ELEMENT set_2_R (Course+)>
<!ELEMENT set_2_S (Course+)>
<!ELEMENT set_2_T (Course+)>
<!ELEMENT set_2_U (Course+)>
<!ELEMENT set_2_V (Course+)>
<!ELEMENT set_2_W (Course+)>
<!ELEMENT set_2_X (Course+)>
<!ELEMENT set_2_Y (Course+)>
<!ELEMENT set_2_Z (Course+)>
<!--Term3-->
<!ELEMENT set_3_A (Course+)>
<!ELEMENT set_3_B (Course+)>
<!ELEMENT set_3_C (Course+)>
<!ELEMENT set_3_D (Course+)>
<!ELEMENT set_3_E (Course+)>
<!ELEMENT set_3_F (Course+)>
<!ELEMENT set_3_G (Course+)>
<!ELEMENT set_3_H (Course+)>
<!ELEMENT set_3_I (Course+)>
<!ELEMENT set_3_J (Course+)>
<!ELEMENT set_3_K (Course+)>
<!ELEMENT set_3_L (Course+)>
<!ELEMENT set_3_M (Course+)>
<!ELEMENT set_3_N (Course+)>
<!ELEMENT set_3_O (Course+)>
<!ELEMENT set_3_P (Course+)>
<!ELEMENT set_3_Q (Course+)>
<!ELEMENT set_3_R (Course+)>
<!ELEMENT set_3_S (Course+)>
<!ELEMENT set_3_T (Course+)>
<!ELEMENT set_3_U (Course+)>
<!ELEMENT set_3_V (Course+)>
<!ELEMENT set_3_W (Course+)>
<!ELEMENT set_3_X (Course+)>
<!ELEMENT set_3_Y (Course+)>
<!ELEMENT set_3_Z (Course+)>
<!--Term4-->
<!ELEMENT set_4_A (Course+)>
<!ELEMENT set_4_B (Course+)>
<!ELEMENT set_4_C (Course+)>
<!ELEMENT set_4_D (Course+)>
<!ELEMENT set_4_E (Course+)>
<!ELEMENT set_4_F (Course+)>
<!ELEMENT set_4_G (Course+)>
<!ELEMENT set_4_H (Course+)>
<!ELEMENT set_4_I (Course+)>
<!ELEMENT set_4_J (Course+)>
<!ELEMENT set_4_K (Course+)>
<!ELEMENT set_4_L (Course+)>
<!ELEMENT set_4_M (Course+)>
<!ELEMENT set_4_N (Course+)>
<!ELEMENT set_4_O (Course+)>
<!ELEMENT set_4_P (Course+)>
<!ELEMENT set_4_Q (Course+)>
<!ELEMENT set_4_R (Course+)>
<!ELEMENT set_4_S (Course+)>
<!ELEMENT set_4_T (Course+)>
<!ELEMENT set_4_U (Course+)>
<!ELEMENT set_4_V (Course+)>
<!ELEMENT set_4_W (Course+)>
<!ELEMENT set_4_X (Course+)>
<!ELEMENT set_4_Y (Course+)>
<!ELEMENT set_4_Z (Course+)>
<!--Term5-->
<!ELEMENT set_5_A (Course+)>
<!ELEMENT set_5_B (Course+)>
<!ELEMENT set_5_C (Course+)>
<!ELEMENT set_5_D (Course+)>
<!ELEMENT set_5_E (Course+)>
<!ELEMENT set_5_F (Course+)>
<!ELEMENT set_5_G (Course+)>
<!ELEMENT set_5_H (Course+)>
<!ELEMENT set_5_I (Course+)>
<!ELEMENT set_5_J (Course+)>
<!ELEMENT set_5_K (Course+)>
<!ELEMENT set_5_L (Course+)>
<!ELEMENT set_5_M (Course+)>
<!ELEMENT set_5_N (Course+)>
<!ELEMENT set_5_O (Course+)>
<!ELEMENT set_5_P (Course+)>
<!ELEMENT set_5_Q (Course+)>
<!ELEMENT set_5_R (Course+)>
<!ELEMENT set_5_S (Course+)>
<!ELEMENT set_5_T (Course+)>
<!ELEMENT set_5_U (Course+)>
<!ELEMENT set_5_V (Course+)>
<!ELEMENT set_5_W (Course+)>
<!ELEMENT set_5_X (Course+)>
<!ELEMENT set_5_Y (Course+)>
<!ELEMENT set_5_Z (Course+)>
<!--Term6-->
<!ELEMENT set_6_A (Course+)>
<!ELEMENT set_6_B (Course+)>
<!ELEMENT set_6_C (Course+)>
<!ELEMENT set_6_D (Course+)>
<!ELEMENT set_6_E (Course+)>
<!ELEMENT set_6_F (Course+)>
<!ELEMENT set_6_G (Course+)>
<!ELEMENT set_6_H (Course+)>
<!ELEMENT set_6_I (Course+)>
<!ELEMENT set_6_J (Course+)>
<!ELEMENT set_6_K (Course+)>
<!ELEMENT set_6_L (Course+)>
<!ELEMENT set_6_M (Course+)>
<!ELEMENT set_6_N (Course+)>
<!ELEMENT set_6_O (Course+)>
<!ELEMENT set_6_P (Course+)>
<!ELEMENT set_6_Q (Course+)>
<!ELEMENT set_6_R (Course+)>
<!ELEMENT set_6_S (Course+)>
<!ELEMENT set_6_T (Course+)>
<!ELEMENT set_6_U (Course+)>
<!ELEMENT set_6_V (Course+)>
<!ELEMENT set_6_W (Course+)>
<!ELEMENT set_6_X (Course+)>
<!ELEMENT set_6_Y (Course+)>
<!ELEMENT set_6_Z (Course+)>
<!--Term7-->
<!ELEMENT set_7_A (Course+)>
<!ELEMENT set_7_B (Course+)>
<!ELEMENT set_7_C (Course+)>
<!ELEMENT set_7_D (Course+)>
<!ELEMENT set_7_E (Course+)>
<!ELEMENT set_7_F (Course+)>
<!ELEMENT set_7_G (Course+)>
<!ELEMENT set_7_H (Course+)>
<!ELEMENT set_7_I (Course+)>
<!ELEMENT set_7_J (Course+)>
<!ELEMENT set_7_K (Course+)>
<!ELEMENT set_7_L (Course+)>
<!ELEMENT set_7_M (Course+)>
<!ELEMENT set_7_N (Course+)>
<!ELEMENT set_7_O (Course+)>
<!ELEMENT set_7_P (Course+)>
<!ELEMENT set_7_Q (Course+)>
<!ELEMENT set_7_R (Course+)>
<!ELEMENT set_7_S (Course+)>
<!ELEMENT set_7_T (Course+)>
<!ELEMENT set_7_U (Course+)>
<!ELEMENT set_7_V (Course+)>
<!ELEMENT set_7_W (Course+)>
<!ELEMENT set_7_X (Course+)>
<!ELEMENT set_7_Y (Course+)>
<!ELEMENT set_7_Z (Course+)>
<!--Term8-->
<!ELEMENT set_8_A (Course+)>
<!ELEMENT set_8_B (Course+)>
<!ELEMENT set_8_C (Course+)>
<!ELEMENT set_8_D (Course+)>
<!ELEMENT set_8_E (Course+)>
<!ELEMENT set_8_F (Course+)>
<!ELEMENT set_8_G (Course+)>
<!ELEMENT set_8_H (Course+)>
<!ELEMENT set_8_I (Course+)>
<!ELEMENT set_8_J (Course+)>
<!ELEMENT set_8_K (Course+)>
<!ELEMENT set_8_L (Course+)>
<!ELEMENT set_8_M (Course+)>
<!ELEMENT set_8_N (Course+)>
<!ELEMENT set_8_O (Course+)>
<!ELEMENT set_8_P (Course+)>
<!ELEMENT set_8_Q (Course+)>
<!ELEMENT set_8_R (Course+)>
<!ELEMENT set_8_S (Course+)>
<!ELEMENT set_8_T (Course+)>
<!ELEMENT set_8_U (Course+)>
<!ELEMENT set_8_V (Course+)>
<!ELEMENT set_8_W (Course+)>
<!ELEMENT set_8_X (Course+)>
<!ELEMENT set_8_Y (Course+)>
<!ELEMENT set_8_Z (Course+)>

<!ELEMENT Course (Name,Day,Start_Time,End_Time,Start_Date,End_Date,Room,Max,Act,Hrs,Teacher+)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Day (#PCDATA)>
<!ELEMENT Start_Time (#PCDATA)>
<!ELEMENT End_Time (#PCDATA)>
<!ELEMENT Start_Date (#PCDATA)>
<!ELEMENT End_Date (#PCDATA)>
<!ELEMENT Room (#PCDATA)>
<!ELEMENT Max (#PCDATA)>
<!ELEMENT Act (#PCDATA)>
<!ELEMENT Hrs (#PCDATA)>
<!ELEMENT Teacher (#PCDATA)>

=== Jakob-G/xml_assignment1/data/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classes SYSTEM "classes.dtd">
<classes>
    <Set name='1_A'>
        <Course name='CIVL1011'>
            <Block>
                <Day>Thu</Day>
                <Start_Time>1030</Start_Time>
                <End_Time>1120</End_Time>
                <Start_Date>04 Sep 2018</Start_Date>
                <End_Date>07 Dec 2018</End_Date>
                <Room>SW01 1021</Room>
                <Max>84</Max>
                <Act>81</Act>
                <Hrs>0.83</Hrs>
                <Teacher>Nishimura, Kim</Teacher>
                <Teacher>Gaudet, Jacquie</Teacher>
                <Teacher>Chong, Phyllis Lok-Ting</Teacher>
            </Block>
            <Block>
                <Day>Tue</Day>
                <Start_Time>1230</Start_Time>
                <End_Time>1420</End_Time>
                <Start_Date>05 Sep 2018</Start_Date>
                <End_Date>07 Dec 2018</End_Date>
                <Room>SE12 318</Room>
                <Max>21</Max>
                <Act>21</Act>
                <Hrs>1.83</Hrs>
                <Teacher>Chong, Phyllis Lok-Ting</Teacher>
                <Teacher>* Gaudet, Jacquie</Teacher>
                <Teacher>Nishimura, Kim</Teacher>
            </Block>
        </Course>
    </Set>
</classes>
